# CMake generated Testfile for 
# Source directory: /home/runner/work/libjson/libjson
# Build directory: /home/runner/work/libjson/libjson
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(old_test_json_array_manipulation "/home/runner/work/libjson/libjson/old_test_json_array_manipulation")
set_tests_properties(old_test_json_array_manipulation PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(old_test_json_object_manipulation "/home/runner/work/libjson/libjson/old_test_json_object_manipulation")
set_tests_properties(old_test_json_object_manipulation PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(old_test_json_string_escape "/home/runner/work/libjson/libjson/old_test_json_string_escape")
set_tests_properties(old_test_json_string_escape PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_comments "/home/runner/work/libjson/libjson/test_json5_comments")
set_tests_properties(test_json5_comments PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_compatibility "/home/runner/work/libjson/libjson/test_json5_compatibility")
set_tests_properties(test_json5_compatibility PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_complex_identifiers "/home/runner/work/libjson/libjson/test_json5_complex_identifiers")
set_tests_properties(test_json5_complex_identifiers PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_empty_input "/home/runner/work/libjson/libjson/test_json5_empty_input")
set_tests_properties(test_json5_empty_input PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_file "/home/runner/work/libjson/libjson/test_json5_file")
set_tests_properties(test_json5_file PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_keywords "/home/runner/work/libjson/libjson/test_json5_keywords")
set_tests_properties(test_json5_keywords PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_mixed_features "/home/runner/work/libjson/libjson/test_json5_mixed_features")
set_tests_properties(test_json5_mixed_features PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_quote_mixing "/home/runner/work/libjson/libjson/test_json5_quote_mixing")
set_tests_properties(test_json5_quote_mixing PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_single_quotes "/home/runner/work/libjson/libjson/test_json5_single_quotes")
set_tests_properties(test_json5_single_quotes PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_trailing_commas "/home/runner/work/libjson/libjson/test_json5_trailing_commas")
set_tests_properties(test_json5_trailing_commas PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json5_unquoted_keys "/home/runner/work/libjson/libjson/test_json5_unquoted_keys")
set_tests_properties(test_json5_unquoted_keys PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_array_elements "/home/runner/work/libjson/libjson/test_json_array_elements")
set_tests_properties(test_json_array_elements PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_array_empty "/home/runner/work/libjson/libjson/test_json_array_empty")
set_tests_properties(test_json_array_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_array_push "/home/runner/work/libjson/libjson/test_json_array_push")
set_tests_properties(test_json_array_push PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_copy_complex "/home/runner/work/libjson/libjson/test_json_copy_complex")
set_tests_properties(test_json_copy_complex PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_copy_empty_array "/home/runner/work/libjson/libjson/test_json_copy_empty_array")
set_tests_properties(test_json_copy_empty_array PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_copy_empty_object "/home/runner/work/libjson/libjson/test_json_copy_empty_object")
set_tests_properties(test_json_copy_empty_object PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_copy_object "/home/runner/work/libjson/libjson/test_json_copy_object")
set_tests_properties(test_json_copy_object PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_default_errbuf_failure "/home/runner/work/libjson/libjson/test_json_default_errbuf_failure")
set_tests_properties(test_json_default_errbuf_failure PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_default_errbuf_success "/home/runner/work/libjson/libjson/test_json_default_errbuf_success")
set_tests_properties(test_json_default_errbuf_success PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_false "/home/runner/work/libjson/libjson/test_json_false")
set_tests_properties(test_json_false PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_null "/home/runner/work/libjson/libjson/test_json_null")
set_tests_properties(test_json_null PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_number "/home/runner/work/libjson/libjson/test_json_number")
set_tests_properties(test_json_number PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_number_boundary "/home/runner/work/libjson/libjson/test_json_number_boundary")
set_tests_properties(test_json_number_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_object_empty "/home/runner/work/libjson/libjson/test_json_object_empty")
set_tests_properties(test_json_object_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_object_remove "/home/runner/work/libjson/libjson/test_json_object_remove")
set_tests_properties(test_json_object_remove PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_invalid_array_token "/home/runner/work/libjson/libjson/test_json_read_invalid_array_token")
set_tests_properties(test_json_read_invalid_array_token PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_invalid_null_token "/home/runner/work/libjson/libjson/test_json_read_invalid_null_token")
set_tests_properties(test_json_read_invalid_null_token PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_invalid_number_token "/home/runner/work/libjson/libjson/test_json_read_invalid_number_token")
set_tests_properties(test_json_read_invalid_number_token PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_invalid_object_token "/home/runner/work/libjson/libjson/test_json_read_invalid_object_token")
set_tests_properties(test_json_read_invalid_object_token PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_invalid_string_token "/home/runner/work/libjson/libjson/test_json_read_invalid_string_token")
set_tests_properties(test_json_read_invalid_string_token PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_multiple_invalid_tokens "/home/runner/work/libjson/libjson/test_json_read_multiple_invalid_tokens")
set_tests_properties(test_json_read_multiple_invalid_tokens PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_read_success "/home/runner/work/libjson/libjson/test_json_read_success")
set_tests_properties(test_json_read_success PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_string_creation "/home/runner/work/libjson/libjson/test_json_string_creation")
set_tests_properties(test_json_string_creation PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_true "/home/runner/work/libjson/libjson/test_json_true")
set_tests_properties(test_json_true PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_type_checking "/home/runner/work/libjson/libjson/test_json_type_checking")
set_tests_properties(test_json_type_checking PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_json_write_read "/home/runner/work/libjson/libjson/test_json_write_read")
set_tests_properties(test_json_write_read PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_arrays "/home/runner/work/libjson/libjson/test_yaml_arrays")
set_tests_properties(test_yaml_arrays PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_boolean "/home/runner/work/libjson/libjson/test_yaml_boolean")
set_tests_properties(test_yaml_boolean PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_booleans "/home/runner/work/libjson/libjson/test_yaml_booleans")
set_tests_properties(test_yaml_booleans PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_comments "/home/runner/work/libjson/libjson/test_yaml_comments")
set_tests_properties(test_yaml_comments PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_empty "/home/runner/work/libjson/libjson/test_yaml_empty")
set_tests_properties(test_yaml_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_error_handling "/home/runner/work/libjson/libjson/test_yaml_error_handling")
set_tests_properties(test_yaml_error_handling PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_mixed "/home/runner/work/libjson/libjson/test_yaml_mixed")
set_tests_properties(test_yaml_mixed PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_null "/home/runner/work/libjson/libjson/test_yaml_null")
set_tests_properties(test_yaml_null PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_number "/home/runner/work/libjson/libjson/test_yaml_number")
set_tests_properties(test_yaml_number PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_objects "/home/runner/work/libjson/libjson/test_yaml_objects")
set_tests_properties(test_yaml_objects PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_roundtrip "/home/runner/work/libjson/libjson/test_yaml_roundtrip")
set_tests_properties(test_yaml_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_string "/home/runner/work/libjson/libjson/test_yaml_string")
set_tests_properties(test_yaml_string PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_strings "/home/runner/work/libjson/libjson/test_yaml_strings")
set_tests_properties(test_yaml_strings PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_write_boolean "/home/runner/work/libjson/libjson/test_yaml_write_boolean")
set_tests_properties(test_yaml_write_boolean PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_write_null "/home/runner/work/libjson/libjson/test_yaml_write_null")
set_tests_properties(test_yaml_write_null PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_write_number "/home/runner/work/libjson/libjson/test_yaml_write_number")
set_tests_properties(test_yaml_write_number PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
add_test(test_yaml_write_string "/home/runner/work/libjson/libjson/test_yaml_write_string")
set_tests_properties(test_yaml_write_string PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/libjson/libjson/CMakeLists.txt;21;add_test;/home/runner/work/libjson/libjson/CMakeLists.txt;0;")
